version: 0.1
debug: true
language: en
max_activation_queue_operations: 5
class:
  activation_cooldown: 10
################
# Archer Class #
################
  archer:
    active: true
    tag_time: 10
    # Damage multiplier should be an integer, the percentile is handled internally
    damage_multiplier: 7
    buff:
      type: "speed"
      level: 2
##############
# Bard Class #
##############
  bard:
    active: true
    effect:
      range: 20
      default_duration: 5
      amplified_duration: 10
      speed:
        level: 2
        amplified: 3
      strength:
        level: 2
        amplified: 4
      haste:
        level: 2
        amplified: 3
      regeneration:
        level: 2
        amplified: 4
    horn_cooldown: 60
###############
# Rogue Class #
###############
  rogue:
    active: true
    knife:
      throw_cooldown: 3
#################
# Warrior Class #
#################
  warrior:
    active: true
  # No configurations available for warrior class

